Feature/allocation score
BenDundon/TeacherAllocationSystem-2023 pull request #12
Opened 2023-09-24 00:32 UTC by BenDundon

Adds a data type to score an allocation of an academic to a unit. Written this time in TypeScript as that's what Adonis expects according to their docs, however won't be fully testable until CPF-36 completes as nothing calls this code yet.

2023-09-26 11:25 UTC, TsubasaBneAus requested changes
@BenDundon 
I have reviewed your codes and left some comments on them. Please have a look at them!

2023-09-26 11:25 UTC, TsubasaBneAus commented on tas/app/Models/formResponses.ts
@BenDundon 
- Values of the scales for **willingness** and **expertise** should be changed to the 1-10 scale as I mentioned in **academic preference form** branch.
- Indent size should be changed to 2 using like **Prettier** to keep all files have the same indent size

2023-09-26 11:25 UTC, TsubasaBneAus commented on tas/app/Controllers/Http/AutoAllocatorController.ts
@BenDundon 
- You should format this script to organise the codes using **Prettier**, and the indent size should be changed to 2 that is the same as its size in other source codes.

2023-09-26 14:57 UTC, TsubasaBneAus requested changes

2023-09-26 14:57 UTC, TsubasaBneAus commented on tas/.env.example
@BenDundon 
The value of **HOST** in the .env.example file should be changed to **localhost** to make it easier for developers to understand how the server of this app runs.
This issue is not related to the main problem, but it is better to change it.

2023-09-26 17:43 UTC, merged

2023-10-08 02:29 UTC, BenDundon commented on tas/.env.example
Hi @TsubasaBneAus, `0.0.0.0` refers the same as `localhost`, as it directs to the **default route**, which on a user device is `127.0.0.1` (`localhost`).